# Install requirede libraries
devtools::install_github("ilarischeinin/rasterpdf")
devtools::install('meta', repos = 'http://cran.us.r-project.org' )
devtools::install('tibble')
devtools::install('dplyr')
devtools::install('tidyverse')
devtools::install('stringr')
devtools::install('meta') # Forest Plot
devtools::install('ggplot2')
devtools::install('VennDiagram')
devtools::install('RColorBrewer')
devtools::install('reshape')
devtools::install('ggsignif')
devtools::install('tools')
devtools::install('BiocManager')
# Bioconductor
BiocManager::install( "missMethyl" )
BiocManager::install( "org.Hs.eg.db" )
BiocManager::install( "GenomicRanges" )
BiocManager::install( "rtracklayer" )
