# Install requirede libraries
devtools::install_github("ilarischeinin/rasterpdf")
devtools::install_github("guido-s/meta")
devtools::install_version('tidyverse', version = '1.3.0')
devtools::install_version('dplyr', version = '1.0.2')
devtools::install_version('tidyverse', version = '1.3.0')
devtools::install_version('stringr', version = '1.4.0')
devtools::install_version('ggplot2', version = '3.3.2')
devtools::install_version('VennDiagram', version = '1.6.20')
devtools::install_version('RColorBrewer', version = '1.1-2')
devtools::install_version('reshape2', version = '1.4.4')
devtools::install_version('ggsignif', version = '0.6.0')
devtools::install_version('tools', version = '3.6.3')
devtools::install_version('BiocManager', version = '1.30.10')
# Bioconductor
BiocManager::install( "missMethyl" )
BiocManager::install( "org.Hs.eg.db" )
BiocManager::install( "GenomicRanges" )
BiocManager::install( "rtracklayer" )
# EASIER
devtools::install_github("isglobal-brge/EASIER@HEAD")
